# Generated by Django 4.2.7 on 2024-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_repy_review_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intemediate', 'Intemediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
